AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    8d708b1e-9182-4534-9e57-c045eb939215:
      size:
        width: 60
        height: 60
      position:
        x: 357
        'y': 223
      z: 0
      embeds: []
    2280bcf3-ad14-4c6e-8c63-ddb05cc8f533:
      size:
        width: 60
        height: 60
      position:
        x: 444
        'y': 243.75
      z: 0
      embeds: []
      isassociatedwith:
        - 8d708b1e-9182-4534-9e57-c045eb939215
    073c4e89-8950-4545-9b34-39c4db361145:
      size:
        width: 60
        height: 60
      position:
        x: 282.1666666666667
        'y': 278.2916666666667
      z: 0
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: hack3rlife.website
      WebsiteConfiguration:
        IndexDocument: index.html
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8d708b1e-9182-4534-9e57-c045eb939215
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2280bcf3-ad14-4c6e-8c63-ddb05cc8f533
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties: 
      DistributionConfig: 
        Origins:
          - Id: myS3Bucket
            DomainName: hack3rlife.website.s3-website.us-east-2.amazonaws.com
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: myS3Bucket
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 073c4e89-8950-4545-9b34-39c4db361145